FROM openjdk:11-jdk

RUN apt-get -y update

RUN apt-get -y install python

RUN apt-get -y install make \
                        curl \
                        file \
                        ssh

RUN apt-get -y install ruby2.7 \
                        ruby2.7-dev \
                        build-essential ; \
    gem install fastlane